project_id = "hzruvaprvwvpslfvwcdj"

[functions.create-payment]
verify_jwt = false

[functions.tokopay-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.process-fulfillment]
verify_jwt = false

[functions.trigger-fulfillment]
verify_jwt = false